### ISSUE TITLE
Instructions for updating Tensorflow?

### ISSUE THREAD

**Issue by reiinakano** [bitfusionio/amis#5]
I tried updating Tensorflow to v1.1.0 but in doing so, the default Tensorflow doesn't use GPU anymore. Rather than figure it out, I had to backup all my notebooks and start a fresh instance of the AMI.

Are there instructions for updating Tensorflow without messing with all the GPU configuration and stuff?

**Comment by mbajkowski** [comment]
Reiichiro,


We've not updated our AMI to TF 1.1 yet. Once we do I can provide you with update instructions on how to upgrade the 1.0.1 version to 1.1. Can you file a ticket here so that we can keep track of the request:


<https://bitfusion.zendesk.com/hc/en-us/restricted?return_to=https%3A%2F%2Fbitfusion.zendesk.com%2Fhc%2Fen-us>https://bitfusion.zendesk.com/


Thanks,


Maciej




________________________________

**Comment by reiinakano** [comment]
Okay, I've submitted the request.

**Comment by reiinakano** [comment]
Okay, I've submitted the request. Thank you.
